# Generated by Django 5.2.16 on 2026-07-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_url',
            field=models.URLField(blank=True, help_text='Permanent CV URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Permanent photo URL (e.g. Cloudinary, Imgur, GitHub)', max_length=500, null=True),
        ),
    ]
