# Generated by Django 5.2.16 on 2026-07-20 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(help_text='Skill competency level out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('ai', 'AI'), ('programming', 'Programming Languages'), ('tools', 'Tools')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='React Icon name, e.g., FaReact, SiDjango, SiTypescript', max_length=50)),
            ],
            options={
                'ordering': ['category', '-percentage', 'name'],
            },
        ),
    ]
